apiVersion: v1
kind: ConfigMap
metadata:
  name: siembro-user-notes-config
data:
  AUTH0_DOMAIN: "dev-fxabduas3g72jw4m.us.auth0.com"
  AUTH0_AUDIENCE: "https://siembro-user-notes-api"
  AUTH0_ALGORITHMS: "RS256"
  DEBUG: "false"
